### ISSUE TITLE
Could you please offer a sample dataset？

### ISSUE THREAD

**Issue by kaca0083** [AakashKT/pytorch-recurrent-ae-siggraph17#4]
Could you please offer a sample dataset？It will be much easier for testing the code. It will be better if you can offer the code for generating the dataset. Thank you so much!

**Comment by AakashKT** [comment]
Hi,

Unfortunately, I lost all the data which I used to train the network.
However, I suggest you use the scene generation script from here: https://github.com/adobe/sbmc#generating-new-random-scenes-for-training .

The above script generates .pbrt scene files (as far as I know). You can then use PBRT (https://github.com/mmp/pbrt-v3) to directly render these.

The above process should give you a much diverse dataset, since their scene generation script is awesome. 

Thanks,
Aakash

**Comment by kaca0083** [comment]
> Hi,
> 
> Unfortunately, I lost all the data which I used to train the network.
> However, I suggest you use the scene generation script from here: https://github.com/adobe/sbmc#generating-new-random-scenes-for-training .
> 
> The above script generates .pbrt scene files (as far as I know). You can then use PBRT (https://github.com/mmp/pbrt-v3) to directly render these.
> 
> The above process should give you a much diverse dataset, since their scene generation script is awesome.
> 
> Thanks,
> Aakash

Thank you so much！
